lecture_14/lecture_3/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('user.urls')),
    path('', include('shop.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lecture_14/shop/urls.py
from django.urls import path
from .views import products_page_view, product_details_page_view, delete_product_page_view, edit_product_page_view, \
    index_page_view, category_page_view, basket_page_view, add_product_to_basket_view, delete_from_basket_view

urlpatterns = [
    # products/
    path('', index_page_view, name='index_page'),
    path('basket/', basket_page_view, name='basket'),
    path('add_to_basket/<int:pk>', add_product_to_basket_view, name='add_to_basket'),
    path('delete_from_basket/<int:pk>', delete_from_basket_view, name='delete_from_basket'),
    path('categories/<int:pk>', category_page_view, name='category_details_page'),
    path('products/', products_page_view, name='products_page'),
    path('products/<int:pk>', product_details_page_view, name='product_details_page'),
    path('products/<int:pk>/edit', edit_product_page_view, name='edit_product_page'),
    path('products/<int:pk>/delete', delete_product_page_view, name='delete_product_page')
]

lecture_14/user/urls.py
from django.urls import path
from .views import login_page, register_page, handle_logout, profile_page_view, forgot_password_view, \
    reset_password_view

urlpatterns = [
    # products/
    path('login/', login_page, name='login-page'),
    path('register/', register_page, name='register-page'),
    path('logout/', handle_logout, name='logout'),
    path('settings/', profile_page_view, name='settings_page'),
    path('forgot-password/', forgot_password_view, name='forgot_password_page'),
    path('reset-password/<slug:token>', reset_password_view, name='reset_password_page'),
]

lecture_14/user/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    avatar = models.ImageField(upload_to='user/', null=True, max_length=2000)
    bio = models.TextField(max_length=2000, null=False, blank=True)
    owner = models.OneToOneField(User, on_delete=models.CASCADE, null=False)
    resume = models.FileField(upload_to='user/', null=True, max_length=2000)

    class Meta:
        verbose_name = 'Profile'
        verbose_name_plural = 'Profiles'

    def __str__(self):
        return f'{self.id} {self.owner.username}'


class ResetPassword(models.Model):
    email = models.EmailField(null=False, blank=False, max_length=255)
    token = models.CharField(null=False, blank=False, max_length=255)
    created_at = models.DateTimeField(null=False, auto_now_add=True)

    class Meta:
        verbose_name = 'Reset Password'
        verbose_name_plural = 'Reset Passwords'

    def __str__(self):
        return f'{self.id} {self.email} {self.token} {self.created_at}'

lecture_14/user/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile


class LoginForm(forms.Form):
    username = forms.CharField(required=True, min_length=4, max_length=20,
                               widget=forms.TextInput({'class': 'form-control', 'type': 'text'}))
    password = forms.CharField(min_length=8, max_length=20,
                               widget=forms.PasswordInput({'class': 'form-control', 'type': 'password'}))


class ForgotPasswordForm(forms.Form):
    email = forms.EmailField(required=True, min_length=4, max_length=200,
                             widget=forms.TextInput({'class': 'form-control', 'type': 'email'}))


class RegisterForm(forms.ModelForm):
    repeat_password = forms.CharField(required=True, min_length=8, max_length=20,
                                      widget=forms.PasswordInput({'class': 'form-control', 'type': 'password',
                                                                  'placeholder': 'Repeat your password'}))

    class Meta:
        model = User
        fields = ['email', 'username', 'first_name', 'last_name', 'password']
        widgets = {
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Enter your email'}),
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter your username'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter your first name'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter your last name'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Enter your password'}),
        }

    def clean_repeat_password(self):
        password1 = self.cleaned_data.get("password")
        password2 = self.cleaned_data.get("repeat_password")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords do not match")
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user


class ResetPasswordForm(forms.Form):
    password = forms.CharField(required=True, min_length=8, max_length=20,
                               widget=forms.PasswordInput({'class': 'form-control', 'type': 'password',
                                                           'placeholder': 'Enter your password'}))
    repeat_password = forms.CharField(required=True, min_length=8, max_length=20,
                                      widget=forms.PasswordInput({'class': 'form-control', 'type': 'password',
                                                                  'placeholder': 'Repeat your password'}))

    def clean_repeat_password(self):
        password1 = self.cleaned_data.get("password")
        password2 = self.cleaned_data.get("repeat_password")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords do not match")
        return password2


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['bio']
        widgets = {
            'bio': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter your bio'}),
        }

lecture_14/user/views.py
from django.shortcuts import render, redirect
from .forms import LoginForm, RegisterForm, ProfileForm, ForgotPasswordForm, ResetPasswordForm
from django.contrib.auth.models import auth
from django.contrib.auth import login
from .models import Profile, ResetPassword
from django import template
from django.core.mail import send_mail
from datetime import datetime, timezone
from django.contrib.auth.models import User

import uuid

RESET_PASSWORD_TOKEN_EXPIRATION_PERIOD = 2 * 60 * 60


def login_page(request):
    if request.method == 'GET':
        form = LoginForm()
        return render(request, 'user/login.html', {'form': form})
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            user = auth.authenticate(username=form.data.get('username'), password=form.data.get('password'))
            login(request, user)
            if user is not None:
                return redirect('/')
            else:
                form.add_error(field='username', error='Invalid password or login')
                return render(request, 'user/login.html', {'form': form})
        else:
            return render(request, 'user/login.html', {'form': form})


def register_page(request):
    if request.method == 'GET':
        form = RegisterForm()
        return render(request, 'user/register.html', {'form': form})
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            profile = Profile(owner_id=user.id)
            profile.save()
            auth_data = auth.authenticate(request, email=user.email, password=form.data.get('password'))
            if auth_data is not None:
                login(request, auth_data)
                return redirect('/')
            return redirect('/auth/login/')
        return render(request, 'user/register.html', {'form': form})


def handle_logout(request):
    auth.logout(request)
    return redirect('/auth/login')


def profile_page_view(request):
    if request.user.is_authenticated:
        profile = Profile.objects.get(owner_id=request.user.id)
        if request.method == 'GET':
            form = ProfileForm(data={'bio': profile.bio}, files={'avatar': profile.avatar, 'resume': profile.resume})
            return render(request, 'user/settings.html', {'form': form, 'profile': profile})
        if request.method == 'POST':
            form = ProfileForm(request.POST, request.FILES)
            if form.is_valid():
                if form.files.get('avatar'):
                    profile.avatar = form.files.get('avatar')
                if form.files.get('resume'):
                    profile.resume = form.files.get('resume')
                profile.bio = form.data.get('bio')
                profile.save()
                return render(request, 'user/settings.html', {'form': form, 'profile': profile})
            else:
                return render(request, 'user/settings.html', {'form': form, 'profile': profile})
    else:
        return redirect('/auth/login/')


def forgot_password_view(request):
    if request.method == 'GET':
        form = ForgotPasswordForm()
        return render(request, 'user/forgot-password.html', {'form': form})
    if request.method == 'POST':
        form = ForgotPasswordForm(request.POST)
        if form.is_valid():
            email = form.data.get('email')
            token = uuid.uuid4()
            reset_password = ResetPassword(email=email, token=token)
            reset_password.save()
            email_template = template.loader.get_template('user/reset-password-mail.html')
            email_content = email_template.render(
                {'URL': 'http://localhost:8000/auth/reset-password',
                 'TOKEN': token})
            try:
                send_mail(subject='Reset Your Password', message='', html_message=email_content,
                          from_email='settings.EMAIL_HOST_USER', recipient_list=[email], fail_silently=False)
                return render(request, 'user/forgot-password.html', {'form': form, 'status': 'success'})
            except:
                return render(request, 'user/forgot-password.html', {'form': form, 'status': 'failed'})
        else:
            return render(request, 'user/forgot-password.html', {'form': form})


def reset_password_view(request, token):
    if request.method == 'GET':
        form = ResetPasswordForm()
        try:
            reset_password = ResetPassword.objects.get(token=token)
            email = reset_password.email
            created_at = reset_password.created_at
            if (datetime.now(timezone.utc) - created_at).total_seconds() > RESET_PASSWORD_TOKEN_EXPIRATION_PERIOD:
                reset_password.delete()
                return render(request, 'user/reset-password.html',
                              {'form': form, 'message': 'Your link is expired, please, try again!'})
            else:
                return render(request, 'user/reset-password.html', {'form': form})
        except ResetPassword.DoesNotExist:
            return render(request, 'user/reset-password.html', {'form': form, 'message': 'No data found, try again!'})

    if request.method == 'POST':
        form = ResetPasswordForm(request.POST)
        if form.is_valid():
            try:
                reset_password = ResetPassword.objects.get(token=token)
                email = reset_password.email
                created_at = reset_password.created_at
                if (datetime.now(timezone.utc) - created_at).total_seconds() > RESET_PASSWORD_TOKEN_EXPIRATION_PERIOD:
                    reset_password.delete()
                    return render(request, 'user/reset-password.html',
                                  {'form': form, 'message': 'Your link is expired, please, try again!'})
                else:
                    user = User.objects.get(email=email)
                    user.set_password(form.data.get('password'))
                    user.save()
                    return render(request, 'user/reset-password.html', {'form': form, 'status': 'success'})
            except ResetPassword.DoesNotExist:
                return render(request, 'user/reset-password.html',
                              {'form': form, 'message': 'No data found, try again!'})
        else:
            return render(request, 'user/reset-password.html', {'form': form})

lecture_14/user/templates/user/forgot-password.html
{% extends 'base.html' %}

{% block head %}
<title>Forgot password</title>
<style>
    .login-row {
        min-height: 80vh;
        padding: 100px 0;
    }
</style>
{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12 login-row">
            <div class="col-12">
                {% if status == 'success' %}
                    <div class="alert alert-success" role="alert">
                      Link for password is sent to your email!
                    </div>
                {% endif %}

                {% if status == 'failed' %}
                    <div class="alert alert-danger" role="alert">
                      Something went wrong!
                    </div>
                {% endif %}

                <form name="forgot_password" method="POST" novalidate>
                    <h2>Forgot Password</h2>
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="field-wrapper mt-4">
                        {{ field.label_tag }} {{ field }}
                        <div class="text-danger">
                            {{ field.errors }}
                        </div>
                    </div>
                    {% endfor %}
                    <button class="btn btn-primary d-block col-12 mt-4" type="submit">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

lecture_14/user/templates/user/login.html
{% extends 'base.html' %}

{% block head %}
<title>Login</title>
<style>
    .login-row {
        min-height: 80vh;
        padding: 100px 0;
    }
</style>


{% endblock %}


{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12 login-row">
            <div class="col-12">
                <form name="login" method="POST" novalidate>
                    <h2>Login</h2>
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="field-wrapper mt-4">
                        {{ field.label_tag }} {{ field }}
                        <div class="text-danger">
                            {{ field.errors }}
                        </div>
                    </div>
                    {% endfor %}
                    <button class="btn btn-primary d-block col-12 mt-4" type="submit">Login</button>
                    <a href="/auth/register/" class="d-block text-center mt-4">You dont have an account? Register.</a>
                    <a href="/auth/forgot-password/" class="d-block text-center mt-4">Forgot your password?</a>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

lecture_14/user/templates/user/register.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
  <title>Registration</title>
  <style>
      .field-wrapper {
        margin-top: 10px;
        margin-bottom: 10px;
      }
      .login-row {
        height: 100vh;
        display: flex;
        justify-content: center;
        align-items: center;
      }
  </style>
{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12 login-row">
            <div class="col-2"></div>
            <div class="col-8">
                <form name="registration" method="POST">
                    <h2>Registration</h2>
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="field-wrapper">
                            {{ field.label_tag }}
                            {{ field }}
                            <div class="text-danger">
                                {{ field.errors }}
                            </div>
                        </div>
                    {% endfor %}
                    <button class="btn btn-lg btn-primary btn-block col-12" type="submit">Register</button>
                </form>
            <a href="/auth/login/" class="block">Already signed? Login</a>
            </div>
        </div>
    </div>
  </div>
{% endblock %}

lecture_14/user/templates/user/reset-password-mail.html
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title>HTML email template</title>
    <meta name="viewport" content="width = 375, initial-scale = -1">
  </head>
  <body style="background-color: #ffffff; font-size: 16px;">
    <center>
      <table align="center" border="0" cellpadding="0" cellspacing="0" style="height:100%; width:600px;">
          <!-- BEGIN EMAIL -->
          <tr>
            <td align="center" bgcolor="#ffffff" style="padding:30px">
               <p style="text-align:left">Hello,<br><br> We received a request to reset the password for your account for this email address. To initiate the password reset process for your account, click the link below.
              </p>
              <p>
                <a target="_blank" style="text-decoration:none; background-color: black; border: black 1px solid; color: #fff; padding:10px 10px; display:block;" href="{{URL}}/{{TOKEN}}">
                  <strong>Reset Password</strong>
                </a>
              </p>
              <p style="text-align:left">
              Sincerely,<br>The Django Backend Team
              </p>
            </td>
          </tr>
        </tbody>
      </table>
    </center>
  </body>
</html>

lecture_14/user/templates/user/reset-password.html
{% extends 'base.html' %}

{% block head %}
<title>Reset password</title>
<style>
    .login-row {
        min-height: 80vh;
        padding: 100px 0;
    }
</style>
{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12 login-row">
            <div class="col-12">
                {% if status == 'success' %}
                    <div class="alert alert-success" role="alert">
                      Your password is reset successfully!
                    </div>
                {% endif %}

                {% if status == 'failed' %}
                    <div class="alert alert-danger" role="alert">
                      Something went wrong!
                    </div>
                {% endif %}

                {% if message|length > 0 %}
                    <div class="alert alert-danger" role="alert">
                      {{ message }}
                    </div>
                {% endif %}

                <form name="reset_password" method="POST" novalidate>
                    <h2>Forgot Password</h2>
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="field-wrapper mt-4">
                        {{ field.label_tag }} {{ field }}
                        <div class="text-danger">
                            {{ field.errors }}
                        </div>
                    </div>
                    {% endfor %}
                    <button class="btn btn-primary d-block col-12 mt-4" type="submit">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

lecture_14/user/templates/user/settings.html
{% extends 'base.html' %}

{% block head %}
<title>Settings page</title>
<style>
        .image_input {
            width: 0;
            height: 0;
            overflow: hidden;
        }
        .image-wrapper {
            width: 100px;
            height: 100px;
            border-radius: 50%;
            background-color: #E8E8E8;
            overflow: hidden;
        }

        .image-wrapper img {
            object-fit: cover;
            z-index: 2;
            width: 100%;
            height: 100%;
        }
</style>

{% endblock %}


{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            {% include 'header.html' %}
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-12 my-4">
            <div class="col-12">
                <form method="POST" enctype="multipart/form-data">
                    <h2>Edit your profile</h2>
                    {% csrf_token %}
                    <div class="field-wrapper">
                        <label for="id_avatar">
                            <div class="image-wrapper" id="image-wrapper">
                                {% if profile.avatar %}
                                <img src="{{ profile.avatar.url }}" id="image-content"/>
                                {% endif %}
                            </div>
                            <input id="id_avatar" type="file" name="avatar" accept="image/*" class="image_input"/>
                        </label>
                        <div class="text-danger">
                            {{ form.avatar.errors }}
                        </div>
                    </div>
                    <div class="field-wrapper">
                        {{ form.bio.label_tag }} {{ form.bio }}
                        <div class="text-danger">
                            {{ form.bio.errors }}
                        </div>
                    </div>
                    <div>
                        <label for="id_resume" class="form-label">Upload your resume here:</label>
                        <input name="resume" class="form-control" type="file" id="id_resume"
                               accept="application/pdf,application/vnd.ms-excel">
                        {{ form.resume.errors }}
                        {% if profile.resume %}
                        <a href="{{ profile.resume.url }}" target="_blank">Download</a>
                        {% endif %}
                    </div>
                    <button class="btn btn-primary d-block col-12 mt-2" type="submit">Edit</button>
                </form>
            </div>
        </div>
    </div>
</div>
<script>
    const imageInput = document.getElementById("id_avatar");
    if (imageInput) {
          imageInput.onchange = evt => {
            const [file] = imageInput.files;
            if (file) {
                const newURL = URL.createObjectURL(file);
                const imageElement = document.getElementById('image-content');
                if (imageElement) {
                    imageElement.src = newURL;
                } else {
                    const wrapper = document.getElementById('image-wrapper');
                    const newImageElement = document.createElement('IMG');
                    newImageElement.src = newURL;
                    newImageElement.id = 'image-content';
                    wrapper.appendChild(newImageElement);
                }
            }
        }
    }

</script>
{% endblock %}